release:
  branch: main

success: false # Disables success plugins, which avoids commenting on PR's once released.

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: angular # The angular commit standard
      releaseRules:
        - breaking: true
          release: minor
        - type: feat
          release: patch
        - type: fix
          release: minor
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/github'
