name: checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  checks:
    if: (github.event.pull_request.draft == false) || github.event_name == 'workflow_dispatch'
    name: validate and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        id: setups
        run: |-
          echo "::set-output name=yarn_cache::$(yarn cache dir)"
          echo "::set-output name=node_version::$(cat .nvmrc)"

      - name: Setup Node ${{ steps.setups.outputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.setups.outputs.node_version }}

      - run: yarn

      - run: yarn build
