name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup environment
        id: setups
        run: |-
          echo "::set-output name=yarn_cache::$(yarn cache dir)"
          echo "::set-output name=node_version::$(cat .nvmrc)"

      - name: Setup Node ${{ steps.setups.outputs.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ steps.setups.outputs.node_version }}

      - name: Yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.setups.outputs.yarn_cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-node-${{ steps.setups.outputs.node_version }}

      - run: yarn

      - run: yarn build

      - run: yarn semantic-release
        if: github.event_name == 'push' && github.repository == 'autoguru-au/icons' && github.ref == 'refs/heads/master'
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
