name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rwjblue/setup-volta@v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn semantic-release
        if: github.event_name == 'push' && github.repository == 'autoguru-au/icons' && github.ref == 'refs/heads/master'
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
